<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Hands-on Lab: API Examples
## Random User and Fruityvice API Examples


Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruityvice API, using `requests` Python library
*   Load and use Open-Joke-API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [3]:
%pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (pyproject.toml): started
  Building wheel for randomuser (pyproject.toml): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5128 sha256=d483feee5f3a58a9fdf75253ac928bc22a06c3b762847604782e3202a645e9e5
  Stored in directory: c:\users\z004w1rf\appdata\local\pip\cache\wheels\a8\ce\f1\713605b6f257e4f0efca0fe272df8e2427bd335cf907ab0dff
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Collecting randomuser
  Using cached randomuser-1.6-py3-none-any.whl
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Collecting randomuser
  Using cached randomuser-1.6-py3-none-any.whl
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Note: you may need to restart the kernel to use updated packages.

Then, we will load the necessary libraries.

In [1]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [2]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [3]:
some_list = r.generate_users(10)

In [4]:
some_list

[<randomuser.RandomUser at 0x1f6b5de9e50>,
 <randomuser.RandomUser at 0x1f6b5de9d10>,
 <randomuser.RandomUser at 0x1f6b5d24510>,
 <randomuser.RandomUser at 0x1f6dde495b0>,
 <randomuser.RandomUser at 0x1f6dde69b50>,
 <randomuser.RandomUser at 0x1f6b5ce18c0>,
 <randomuser.RandomUser at 0x1f6dde3a470>,
 <randomuser.RandomUser at 0x1f6dde37c50>,
 <randomuser.RandomUser at 0x1f6dde36850>,
 <randomuser.RandomUser at 0x1f6b5b25b80>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [9]:
name = r.get_full_name()
type(name)
print(name)

Michelle Ray

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [6]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Agron Roy   agron.roy@example.com
Sarah Lo   sarah.lo@example.com
Paula Peña   paula.pena@example.com
Joel Lawson   joel.lawson@example.com
Veeti Murto   veeti.murto@example.com
Cirilo Caldeira   cirilo.caldeira@example.com
محمدامين جعفری   mhmdmyn.jaafry@example.com
Kaïs Lambert   kais.lambert@example.com
Yolanda Black   yolanda.black@example.com
Isabella Chen   isabella.chen@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [ ]:
from PIL import Image
## Write your code here
random_resp = RandomUser()

random_list = random_resp.generate_users(10)

for random_user in random_list:
    photo = random_user.get_picture()

OSError: [Errno 22] Invalid argument: 'https://randomuser.me/api/portraits/women/28.jpg'

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [12]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [13]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Buse Paksüt,female,Denizli,Eskişehir,buse.paksut@example.com,1958-07-24T17:08:36.076Z,https://randomuser.me/api/portraits/women/37.jpg
1,Sharron Perkins,female,Oranmore,Leitrim,sharron.perkins@example.com,1980-03-26T10:44:58.814Z,https://randomuser.me/api/portraits/women/83.jpg
2,Afşar Ekşioğlu,female,Bilecik,Bursa,afsar.eksioglu@example.com,1998-08-26T13:17:35.854Z,https://randomuser.me/api/portraits/women/74.jpg
3,Tobias Navis,male,Hooge Mierde,Noord-Holland,tobias.navis@example.com,1978-11-01T23:34:54.870Z,https://randomuser.me/api/portraits/men/30.jpg
4,Victoria Gauthier,female,Victoria,Alberta,victoria.gauthier@example.com,1958-08-28T09:45:56.420Z,https://randomuser.me/api/portraits/women/81.jpg
5,Ylva Innvær,female,Høle,Trøndelag,ylva.innvaer@example.com,1981-07-07T13:46:20.276Z,https://randomuser.me/api/portraits/women/65.jpg
6,آرش علیزاده,male,زنجان,همدان,arsh.aalyzdh@example.com,1958-09-13T04:34:11.865Z,https://randomuser.me/api/portraits/men/84.jpg
7,Jasmin Bjørgen,female,Lillesand,Sør-Trøndelag,jasmin.bjorgen@example.com,1953-08-13T23:21:57.268Z,https://randomuser.me/api/portraits/women/9.jpg
8,Sylvia Welch,female,Launceston,Queensland,sylvia.welch@example.com,1963-10-09T07:36:31.149Z,https://randomuser.me/api/portraits/women/34.jpg
9,Christian Berry,male,Ballinasloe,Cork City,christian.berry@example.com,1995-04-04T02:55:13.253Z,https://randomuser.me/api/portraits/men/54.jpg

In [14]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [15]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using `requests.get("url")` function. The data is in a json format.

In [16]:
data = requests.get("https://fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [17]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [19]:
df2 = pd.json_normalize(results)

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [21]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [23]:
# Write your code here
banana = df2.loc[df2['name'] == 'Banana']
banana.iloc[0]['nutritions.calories']

np.int64(96)

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get("url")` function, load the data from the URL.

In [24]:
# Write your code here
import requests

jokes_response = requests.get('https://official-joke-api.appspot.com/jokes/ten')

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
```

</details>

2. Retrieve results using `json.loads()` function.

In [27]:
# Write your code here
jokes_results = json.loads(jokes_response.text)
jokes_results

[{'type': 'programming',
  'setup': 'Why did the programmer bring a broom to work?',
  'punchline': 'To clean up all the bugs.',
  'id': 446},
 {'type': 'general',
  'setup': 'What do birds give out on Halloween?',
  'punchline': 'Tweets.',
  'id': 187},
 {'type': 'general',
  'setup': 'What’s E.T. short for?',
  'punchline': 'He’s only got little legs.',
  'id': 276},
 {'type': 'general',
  'setup': 'What biscuit does a short person like?',
  'punchline': 'Shortbread. ',
  'id': 155},
 {'type': 'general',
  'setup': 'Why does Waldo only wear stripes?',
  'punchline': "Because he doesn't want to be spotted.",
  'id': 388},
 {'type': 'programming',
  'setup': 'Why do C# and Java developers keep breaking their keyboards?',
  'punchline': 'Because they use a strongly typed language.',
  'id': 73},
 {'type': 'general',
  'setup': 'Why did the coffee file a police report?',
  'punchline': 'It got mugged.',
  'id': 319},
 {'type': 'general',
  'setup': "Why can't a bicycle stand on its own?",
  'punchline': "It's two-tired.",
  'id': 306},
 {'type': 'general',
  'setup': 'What kind of pants do ghosts wear?',
  'punchline': 'Boo jeans.',
  'id': 256},
 {'type': 'general',
  'setup': "Did you hear about the chameleon who couldn't change color?",
  'punchline': 'They had a reptile dysfunction.',
  'id': 85}]

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3. Convert json data into *pandas* data frame. Drop the type and id columns.

In [28]:
# Write your code here


df = pd.DataFrame(jokes_results)
df

,type,setup,punchline,id
0,programming,Why did the programmer bring a broom to work?,To clean up all the bugs.,446
1,general,What do birds give out on Halloween?,Tweets.,187
2,general,What’s E.T. short for?,He’s only got little legs.,276
3,general,What biscuit does a short person like?,Shortbread.,155
4,general,Why does Waldo only wear stripes?,Because he doesn't want to be spotted.,388
5,programming,Why do C# and Java developers keep breaking th...,Because they use a strongly typed language.,73
6,general,Why did the coffee file a police report?,It got mugged.,319
7,general,Why can't a bicycle stand on its own?,It's two-tired.,306
8,general,What kind of pants do ghosts wear?,Boo jeans.,256
9,general,Did you hear about the chameleon who couldn't ...,They had a reptile dysfunction.,85

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3
```

</details>

# Congratulations! - You have completed the lab

## Author
<a href="https://www.linkedin.com/in/svitlana-kramar" target="_blank">Svitlana Kramar</a>

Svitlana is a master’s degree Data Science and Analytics student at University of Calgary, who enjoys travelling, learning new languages and cultures and loves spreading her passion for Data Science.

## Additional Contributor
<a href="https://www.linkedin.com/in/abhishek-gagneja-23051987/" target="_blank">Abhishek Gagneja</a>

Copyright © 2023 IBM Corporation. All rights reserved.